#!/usr/bin/env node

/**
 * Lists missing translations of a multilingual clone and writes them to
 * docs/i18n/MISSING_TRANSLATIONS.md. Never translates anything — it only reports.
 *
 * Checks:
 *   1. UI strings: every key of the default locale file (src/i18n/<default>.ts)
 *      that another locale file does not define (t() falls back to the default locale).
 *   2. Content entries: every <content>/<collection>/<entry>/ directory that has
 *      no <locale>.md / <locale>.mdx for one of the locales (<content> is src/content/
 *      or, in projects that keep it at the root, content/).
 *
 * Usage: node scripts/i18n-missing.mjs [--root <project>] [--out <path>]
 * Requires Node 24+ (imports the .ts locale files via built-in type stripping).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const arg = (name) => {
  const i = process.argv.indexOf(name);
  return i > -1 ? process.argv[i + 1] : undefined;
};
const ROOT = resolve(arg('--root') ?? join(dirname(fileURLToPath(import.meta.url)), '..'));
const I18N_DIR = join(ROOT, 'src', 'i18n');
const CONTENT_DIR = [join(ROOT, 'src', 'content'), join(ROOT, 'content')].find((dir) => existsSync(dir));
const OUT = resolve(ROOT, arg('--out') ?? 'docs/i18n/MISSING_TRANSLATIONS.md');
const LOCALE_FILE = /^([a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*)\.ts$/;

if (!existsSync(I18N_DIR)) {
  console.log('No src/i18n/ — project is not multilingual, nothing to check.');
  process.exit(0);
}

// --- Locales ---

const indexSource = readFileSync(join(I18N_DIR, 'index.ts'), 'utf8');
const defaultLocale = indexSource.match(/export const defaultLocale(?:\s*:\s*[^=]+)?\s*=\s*["']([^"']+)["']/)?.[1];
if (!defaultLocale) {
  console.error('Error: could not find `export const defaultLocale = "..."` in src/i18n/index.ts');
  process.exit(1);
}

const locales = readdirSync(I18N_DIR)
  .map((file) => file.match(LOCALE_FILE)?.[1])
  .filter(Boolean);
if (!locales.includes(defaultLocale)) {
  console.error(`Error: default locale file src/i18n/${defaultLocale}.ts not found`);
  process.exit(1);
}

// --- 1. UI strings ---

async function loadLocale(locale) {
  const mod = await import(pathToFileURL(join(I18N_DIR, `${locale}.ts`)).href);
  // `export default pl` or a named `export const pl = {...}`
  return mod.default ?? mod[locale] ?? mod[locale.replace(/-/g, '_')];
}

function flatten(node, prefix = '', out = new Map()) {
  for (const [key, value] of Object.entries(node ?? {})) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') out.set(path, value);
    else if (value && typeof value === 'object') flatten(value, path, out);
  }
  return out;
}

const defaultStrings = flatten(await loadLocale(defaultLocale));
const missingStrings = []; // { locale, key, source }
for (const locale of locales.filter((l) => l !== defaultLocale)) {
  const strings = flatten(await loadLocale(locale));
  for (const [key, source] of defaultStrings) {
    if (!strings.has(key) || strings.get(key).trim() === '') missingStrings.push({ locale, key, source });
  }
}

// --- 2. Content entries ---

function frontmatterField(file, field) {
  const fm = readFileSync(file, 'utf8').match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] ?? '';
  return fm.match(new RegExp(`^${field}:\\s*["']?(.*?)["']?\\s*$`, 'm'))?.[1] ?? '';
}

const missingEntries = []; // { entry, locale, sourceFile, title, path }
const isDir = (p) => statSync(p).isDirectory();
if (CONTENT_DIR) {
  for (const collection of readdirSync(CONTENT_DIR).filter((c) => isDir(join(CONTENT_DIR, c)))) {
    const collectionDir = join(CONTENT_DIR, collection);
    for (const entry of readdirSync(collectionDir).filter((e) => isDir(join(collectionDir, e)))) {
      const entryDir = join(collectionDir, entry);
      const files = readdirSync(entryDir);
      const fileFor = (locale) => files.find((f) => f === `${locale}.md` || f === `${locale}.mdx`);
      const present = locales.filter(fileFor);
      if (present.length === 0) continue;
      const sourceLocale = present.includes(defaultLocale) ? defaultLocale : present[0];
      const sourceFile = join(entryDir, fileFor(sourceLocale));
      for (const locale of locales.filter((l) => !fileFor(l))) {
        missingEntries.push({
          entry: `${collection}/${entry}`,
          locale,
          sourceFile: relative(ROOT, sourceFile),
          title: frontmatterField(sourceFile, 'title'),
          path: frontmatterField(sourceFile, 'path'),
        });
      }
    }
  }
}

// --- Report ---

const cell = (text) => String(text).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const lines = [
  '# Missing translations',
  '',
  `Generated by \`node scripts/i18n-missing.mjs\`. Default locale: \`${defaultLocale}\`. Locales: ${locales.map((l) => `\`${l}\``).join(', ')}.`,
  '',
  'Nothing here was machine-translated. UI strings fall back to the default locale until translated; content entries have no route in the missing locale.',
  '',
  `## UI strings (${missingStrings.length})`,
  '',
];
if (missingStrings.length === 0) lines.push('None.');
else {
  lines.push('| Locale | Key | Source text (' + defaultLocale + ') |', '|---|---|---|');
  for (const m of missingStrings) lines.push(`| ${m.locale} | \`${m.key}\` | ${cell(m.source)} |`);
}
lines.push('', `## Content entries (${missingEntries.length})`, '');
if (missingEntries.length === 0) lines.push('None.');
else {
  lines.push('| Locale | Entry | Missing file | Source | Title | Source path |', '|---|---|---|---|---|---|');
  for (const m of missingEntries) {
    const missingFile = `${relative(ROOT, CONTENT_DIR)}/${m.entry}/${m.locale}${m.sourceFile.endsWith('.mdx') ? '.mdx' : '.md'}`;
    lines.push(`| ${m.locale} | \`${m.entry}\` | \`${missingFile}\` | \`${m.sourceFile}\` | ${cell(m.title)} | ${cell(m.path)} |`);
  }
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
console.log(`Missing translations: ${missingStrings.length} UI strings, ${missingEntries.length} content entries → ${relative(ROOT, OUT)}`);
